# build environment
FROM node:16 as build
WORKDIR /client
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production environment
FROM nginx:latest
COPY --from=build /client/dist /usr/share/nginx/html
EXPOSE 3500
CMD ["nginx", "-g", "daemon off;"]