version: '3'
services:
  client:
    build: ./client
    ports:
      - '3500:3500'
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - '27017:27017'